export const ADD_USER = 'ADD_USER';
export const REMOVE_USER = 'REMOVE_USER';

export const ADD_PRODUCT_TO_FAV = 'ADD_PRODUCT_TO_FAV';
export const DELETE_PRODUCT_FROM_FAV = 'DELETE_PRODUCT_FROM_FAV';
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const DELETE_PRODUCT_FROM_CART = 'DELETE_PRODUCT_FROM_CART';
